[package]
name = "wscli"
version = "0.1.0"
authors = ["jakk"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
websocket = {git = "https://github.com/deadjakk/rust-websocket"}
structopt = "0.3.21"
